cmake_minimum_required(VERSION 4.0)
project(libs)

set(CMAKE_CXX_STANDARD 14)

include_directories(androidfw/include)
include_directories(androidfw/include/androidfw)
include_directories(androidfw/include_pathutils)
include_directories(androidfw/include_pathutils/androidfw)
include_directories(androidfw/tests)
include_directories(androidfw/tests/data)
include_directories(androidfw/tests/data/app)
include_directories(androidfw/tests/data/appaslib)
include_directories(androidfw/tests/data/basic)
include_directories(androidfw/tests/data/flagged)
include_directories(androidfw/tests/data/lib_one)
include_directories(androidfw/tests/data/lib_two)
include_directories(androidfw/tests/data/libclient)
include_directories(androidfw/tests/data/overlay)
include_directories(androidfw/tests/data/overlayable)
include_directories(androidfw/tests/data/sparse)
include_directories(androidfw/tests/data/styles)
include_directories(androidfw/tests/data/system)
include_directories(hostgraphics/include)
include_directories(hostgraphics/include/gui)
include_directories(hostgraphics/include/ui)
include_directories(hwui)
include_directories(hwui/apex)
include_directories(hwui/apex/include)
include_directories(hwui/apex/include/android)
include_directories(hwui/apex/include/android/graphics)
include_directories(hwui/canvas)
include_directories(hwui/effects)
include_directories(hwui/hwui)
include_directories(hwui/jni)
include_directories(hwui/jni/fonts)
include_directories(hwui/jni/pdf)
include_directories(hwui/pipeline/skia)
include_directories(hwui/platform/android)
include_directories(hwui/platform/android/pipeline)
include_directories(hwui/platform/android/pipeline/skia)
include_directories(hwui/platform/android/thread)
include_directories(hwui/platform/host/pipeline)
include_directories(hwui/platform/host/pipeline/skia)
include_directories(hwui/platform/host/thread)
include_directories(hwui/platform/host/utils)
include_directories(hwui/private)
include_directories(hwui/private/hwui)
include_directories(hwui/renderstate)
include_directories(hwui/renderthread)
include_directories(hwui/service)
include_directories(hwui/shader)
include_directories(hwui/tests/common)
include_directories(hwui/tests/common/scenes)
include_directories(hwui/tests/unit)
include_directories(hwui/thread)
include_directories(hwui/utils)
include_directories(incident/include)
include_directories(incident/include/incident)
include_directories(incident/include_priv)
include_directories(incident/include_priv/android)
include_directories(incident/include_priv/android/os)
include_directories(input)
include_directories(input/tests/mocks)
include_directories(nativehelper_jvm)
include_directories(protoutil/include)
include_directories(protoutil/include/android)
include_directories(protoutil/include/android/util)
include_directories(services/include)
include_directories(services/include/android)
include_directories(services/include/android/content)
include_directories(services/include/android/os)
include_directories(storage/include)
include_directories(storage/include/storage)
include_directories(usb/tests/AccessoryChat/accessorychat/linux)
include_directories(usb/tests/AccessoryChat/accessorychat/linux/usb)
include_directories(usb/tests/accessorytest)

add_executable(libs
        androidfw/fuzz/cursorwindow_fuzzer/cursorwindow_fuzzer.cpp
        androidfw/fuzz/resourcefile_fuzzer/resourcefile_fuzzer.cpp
        androidfw/fuzz/resxmlparser_fuzzer/resxmlparser_fuzzer.cpp
        androidfw/include/androidfw/ApkAssets.h
        androidfw/include/androidfw/ApkParsing.h
        androidfw/include/androidfw/Asset.h
        androidfw/include/androidfw/AssetDir.h
        androidfw/include/androidfw/AssetManager.h
        androidfw/include/androidfw/AssetManager2.h
        androidfw/include/androidfw/AssetsProvider.h
        androidfw/include/androidfw/AttributeFinder.h
        androidfw/include/androidfw/AttributeResolution.h
        androidfw/include/androidfw/BackupHelpers.h
        androidfw/include/androidfw/BigBuffer.h
        androidfw/include/androidfw/BigBufferStream.h
        androidfw/include/androidfw/ByteBucketArray.h
        androidfw/include/androidfw/Chunk.h
        androidfw/include/androidfw/CombinedIterator.h
        androidfw/include/androidfw/ConfigDescription.h
        androidfw/include/androidfw/CursorWindow.h
        androidfw/include/androidfw/Errors.h
        androidfw/include/androidfw/FileStream.h
        androidfw/include/androidfw/IDiagnostics.h
        androidfw/include/androidfw/Idmap.h
        androidfw/include/androidfw/Image.h
        androidfw/include/androidfw/LoadedArsc.h
        androidfw/include/androidfw/Locale.h
        androidfw/include/androidfw/LocaleData.h
        androidfw/include/androidfw/LocaleDataLookup.h
        androidfw/include/androidfw/misc.h
        androidfw/include/androidfw/MutexGuard.h
        androidfw/include/androidfw/ObbFile.h
        androidfw/include/androidfw/Png.h
        androidfw/include/androidfw/PosixUtils.h
        androidfw/include/androidfw/ResourceTimer.h
        androidfw/include/androidfw/ResourceTypes.h
        androidfw/include/androidfw/ResourceUtils.h
        androidfw/include/androidfw/Source.h
        androidfw/include/androidfw/StreamingZipInflater.h
        androidfw/include/androidfw/Streams.h
        androidfw/include/androidfw/StringPiece.h
        androidfw/include/androidfw/StringPool.h
        androidfw/include/androidfw/TypeWrappers.h
        androidfw/include/androidfw/Util.h
        androidfw/include/androidfw/ZipFileRO.h
        androidfw/include/androidfw/ZipUtils.h
        androidfw/include_pathutils/androidfw/PathUtils.h
        androidfw/tests/data/app/R.h
        androidfw/tests/data/appaslib/R.h
        androidfw/tests/data/basic/R.h
        androidfw/tests/data/flagged/R.h
        androidfw/tests/data/lib_one/R.h
        androidfw/tests/data/lib_two/R.h
        androidfw/tests/data/libclient/R.h
        androidfw/tests/data/overlay/R.h
        androidfw/tests/data/overlayable/R.h
        androidfw/tests/data/sparse/R.h
        androidfw/tests/data/styles/R.h
        androidfw/tests/data/system/R.h
        androidfw/tests/ApkAssets_test.cpp
        androidfw/tests/ApkParsing_test.cpp
        androidfw/tests/AppAsLib_test.cpp
        androidfw/tests/Asset_test.cpp
        androidfw/tests/AssetManager2_bench.cpp
        androidfw/tests/AssetManager2_test.cpp
        androidfw/tests/AttributeFinder_test.cpp
        androidfw/tests/AttributeResolution_bench.cpp
        androidfw/tests/AttributeResolution_test.cpp
        androidfw/tests/BackupData_test.cpp
        androidfw/tests/BackupHelpers_test.cpp
        androidfw/tests/BenchMain.cpp
        androidfw/tests/BenchmarkHelpers.cpp
        androidfw/tests/BenchmarkHelpers.h
        androidfw/tests/BigBuffer_test.cpp
        androidfw/tests/ByteBucketArray_test.cpp
        androidfw/tests/CombinedIterator_test.cpp
        androidfw/tests/CommonHelpers.cpp
        androidfw/tests/CommonHelpers.h
        androidfw/tests/Config_test.cpp
        androidfw/tests/ConfigDescription_test.cpp
        androidfw/tests/ConfigLocale_test.cpp
        androidfw/tests/CursorWindow_bench.cpp
        androidfw/tests/CursorWindow_test.cpp
        androidfw/tests/DynamicRefTable_test.cpp
        androidfw/tests/FileStream_test.cpp
        androidfw/tests/Generic_bench.cpp
        androidfw/tests/Idmap_test.cpp
        androidfw/tests/LoadedArsc_test.cpp
        androidfw/tests/Locale_test.cpp
        androidfw/tests/LocaleDataLookup_bench.cpp
        androidfw/tests/LocaleDataLookup_test.cpp
        androidfw/tests/NinePatch_test.cpp
        androidfw/tests/ObbFile_test.cpp
        androidfw/tests/PosixUtils_test.cpp
        androidfw/tests/ResourceTimer_test.cpp
        androidfw/tests/ResourceUtils_test.cpp
        androidfw/tests/ResTable_test.cpp
        androidfw/tests/SparseEntry_bench.cpp
        androidfw/tests/Split_test.cpp
        androidfw/tests/StringPiece_test.cpp
        androidfw/tests/StringPool_test.cpp
        androidfw/tests/TestHelpers.cpp
        androidfw/tests/TestHelpers.h
        androidfw/tests/TestMain.cpp
        androidfw/tests/Theme_bench.cpp
        androidfw/tests/Theme_test.cpp
        androidfw/tests/TypeWrappers_test.cpp
        androidfw/tests/ZipUtils_test.cpp
        androidfw/ApkAssets.cpp
        androidfw/ApkParsing.cpp
        androidfw/Asset.cpp
        androidfw/AssetDir.cpp
        androidfw/AssetManager.cpp
        androidfw/AssetManager2.cpp
        androidfw/AssetsProvider.cpp
        androidfw/AttributeResolution.cpp
        androidfw/BackupData.cpp
        androidfw/BackupHelpers.cpp
        androidfw/BigBuffer.cpp
        androidfw/BigBufferStream.cpp
        androidfw/ChunkIterator.cpp
        androidfw/ConfigDescription.cpp
        androidfw/CursorWindow.cpp
        androidfw/FileStream.cpp
        androidfw/Idmap.cpp
        androidfw/LoadedArsc.cpp
        androidfw/Locale.cpp
        androidfw/LocaleData.cpp
        androidfw/LocaleDataLookup.cpp
        androidfw/misc.cpp
        androidfw/NinePatch.cpp
        androidfw/ObbFile.cpp
        androidfw/PathUtils.cpp
        androidfw/Png.cpp
        androidfw/PngChunkFilter.cpp
        androidfw/PngCrunch.cpp
        androidfw/PosixUtils.cpp
        androidfw/ResourceTimer.cpp
        androidfw/ResourceTypes.cpp
        androidfw/ResourceUtils.cpp
        androidfw/StreamingZipInflater.cpp
        androidfw/StringPool.cpp
        androidfw/TypeWrappers.cpp
        androidfw/Util.cpp
        androidfw/ZipFileRO.cpp
        androidfw/ZipUtils.cpp
        hostgraphics/include/gui/BufferItem.h
        hostgraphics/include/gui/BufferItemConsumer.h
        hostgraphics/include/gui/BufferQueue.h
        hostgraphics/include/gui/ConsumerBase.h
        hostgraphics/include/gui/IGraphicBufferConsumer.h
        hostgraphics/include/gui/IGraphicBufferProducer.h
        hostgraphics/include/gui/Surface.h
        hostgraphics/include/ui/Fence.h
        hostgraphics/include/ui/GraphicBuffer.h
        hostgraphics/ADisplay.cpp
        hostgraphics/ANativeWindow.cpp
        hostgraphics/Fence.cpp
        hostgraphics/HostBufferQueue.cpp
        hostgraphics/PublicFormat.cpp
        hwui/apex/include/android/graphics/bitmap.h
        hwui/apex/include/android/graphics/canvas.h
        hwui/apex/include/android/graphics/jni_runtime.h
        hwui/apex/include/android/graphics/matrix.h
        hwui/apex/include/android/graphics/paint.h
        hwui/apex/include/android/graphics/properties.h
        hwui/apex/include/android/graphics/region.h
        hwui/apex/android_bitmap.cpp
        hwui/apex/android_canvas.cpp
        hwui/apex/android_matrix.cpp
        hwui/apex/android_paint.cpp
        hwui/apex/android_region.cpp
        hwui/apex/jni_runtime.cpp
        hwui/apex/LayoutlibLoader.cpp
        hwui/apex/properties.cpp
        hwui/apex/TypeCast.h
        hwui/canvas/CanvasFrontend.cpp
        hwui/canvas/CanvasFrontend.h
        hwui/canvas/CanvasOpBuffer.cpp
        hwui/canvas/CanvasOpBuffer.h
        hwui/canvas/CanvasOpRasterizer.cpp
        hwui/canvas/CanvasOpRasterizer.h
        hwui/canvas/CanvasOpRecorder.cpp
        hwui/canvas/CanvasOpRecorder.h
        hwui/canvas/CanvasOps.h
        hwui/canvas/CanvasOpTypes.h
        hwui/canvas/OpBuffer.h
        hwui/canvas/Points.h
        hwui/effects/GainmapRenderer.cpp
        hwui/effects/GainmapRenderer.h
        hwui/effects/StretchEffect.cpp
        hwui/effects/StretchEffect.h
        hwui/hwui/AnimatedImageDrawable.cpp
        hwui/hwui/AnimatedImageDrawable.h
        hwui/hwui/AnimatedImageThread.cpp
        hwui/hwui/AnimatedImageThread.h
        hwui/hwui/Bitmap.cpp
        hwui/hwui/Bitmap.h
        hwui/hwui/BlurDrawLooper.cpp
        hwui/hwui/BlurDrawLooper.h
        hwui/hwui/Canvas.cpp
        hwui/hwui/Canvas.h
        hwui/hwui/DrawTextFunctor.h
        hwui/hwui/ImageDecoder.cpp
        hwui/hwui/ImageDecoder.h
        hwui/hwui/MinikinSkia.cpp
        hwui/hwui/MinikinSkia.h
        hwui/hwui/MinikinUtils.cpp
        hwui/hwui/MinikinUtils.h
        hwui/hwui/Paint.h
        hwui/hwui/PaintFilter.h
        hwui/hwui/PaintImpl.cpp
        hwui/hwui/Typeface.cpp
        hwui/hwui/Typeface.h
        hwui/jni/fonts/Font.cpp
        hwui/jni/fonts/Font.h
        hwui/jni/fonts/FontFamily.cpp
        hwui/jni/pdf/PdfDocument.cpp
        hwui/jni/pdf/PdfEditor.cpp
        hwui/jni/pdf/PdfUtils.cpp
        hwui/jni/pdf/PdfUtils.h
        hwui/jni/text/GraphemeBreak.cpp
        hwui/jni/text/LineBreaker.cpp
        hwui/jni/text/MeasuredText.cpp
        hwui/jni/text/TextShaper.cpp
        hwui/jni/android_graphics_animation_NativeInterpolatorFactory.cpp
        hwui/jni/android_graphics_animation_RenderNodeAnimator.cpp
        hwui/jni/android_graphics_Canvas.cpp
        hwui/jni/android_graphics_Color.cpp
        hwui/jni/android_graphics_ColorSpace.cpp
        hwui/jni/android_graphics_DisplayListCanvas.cpp
        hwui/jni/android_graphics_drawable_AnimatedVectorDrawable.cpp
        hwui/jni/android_graphics_drawable_VectorDrawable.cpp
        hwui/jni/android_graphics_HardwareBufferRenderer.cpp
        hwui/jni/android_graphics_HardwareRenderer.cpp
        hwui/jni/android_graphics_HardwareRendererObserver.cpp
        hwui/jni/android_graphics_HardwareRendererObserver.h
        hwui/jni/android_graphics_Matrix.cpp
        hwui/jni/android_graphics_Matrix.h
        hwui/jni/android_graphics_Mesh.cpp
        hwui/jni/android_graphics_Picture.cpp
        hwui/jni/android_graphics_RenderNode.cpp
        hwui/jni/android_graphics_TextureLayer.cpp
        hwui/jni/android_nio_utils.cpp
        hwui/jni/android_nio_utils.h
        hwui/jni/android_util_PathParser.cpp
        hwui/jni/AnimatedImageDrawable.cpp
        hwui/jni/Bitmap.cpp
        hwui/jni/Bitmap.h
        hwui/jni/BitmapFactory.cpp
        hwui/jni/BitmapFactory.h
        hwui/jni/BitmapRegionDecoder.cpp
        hwui/jni/BufferUtils.cpp
        hwui/jni/BufferUtils.h
        hwui/jni/ByteBufferStreamAdaptor.cpp
        hwui/jni/ByteBufferStreamAdaptor.h
        hwui/jni/Camera.cpp
        hwui/jni/CanvasProperty.cpp
        hwui/jni/ColorFilter.cpp
        hwui/jni/CreateJavaOutputStreamAdaptor.cpp
        hwui/jni/CreateJavaOutputStreamAdaptor.h
        hwui/jni/FontFamily.cpp
        hwui/jni/FontUtils.cpp
        hwui/jni/FontUtils.h
        hwui/jni/Gainmap.cpp
        hwui/jni/GIFMovie.cpp
        hwui/jni/Graphics.cpp
        hwui/jni/graphics_jni_helpers.h
        hwui/jni/GraphicsJNI.h
        hwui/jni/GraphicsStatsService.cpp
        hwui/jni/HardwareBufferHelpers.cpp
        hwui/jni/HardwareBufferHelpers.h
        hwui/jni/ImageDecoder.cpp
        hwui/jni/ImageDecoder.h
        hwui/jni/Interpolator.cpp
        hwui/jni/JvmErrorReporter.h
        hwui/jni/MaskFilter.cpp
        hwui/jni/MeshSpecification.cpp
        hwui/jni/MimeType.h
        hwui/jni/Movie.cpp
        hwui/jni/Movie.h
        hwui/jni/MovieImpl.cpp
        hwui/jni/NinePatch.cpp
        hwui/jni/NinePatchPeeker.cpp
        hwui/jni/NinePatchPeeker.h
        hwui/jni/Paint.cpp
        hwui/jni/PaintFilter.cpp
        hwui/jni/Path.cpp
        hwui/jni/PathEffect.cpp
        hwui/jni/PathIterator.cpp
        hwui/jni/PathMeasure.cpp
        hwui/jni/Picture.cpp
        hwui/jni/Picture.h
        hwui/jni/Region.cpp
        hwui/jni/RenderEffect.cpp
        hwui/jni/RtlProperties.h
        hwui/jni/RuntimeEffectUtils.cpp
        hwui/jni/RuntimeEffectUtils.h
        hwui/jni/RuntimeXfermode.cpp
        hwui/jni/scoped_nullable_primitive_array.h
        hwui/jni/ScopedParcel.cpp
        hwui/jni/ScopedParcel.h
        hwui/jni/Shader.cpp
        hwui/jni/Typeface.cpp
        hwui/jni/Utils.cpp
        hwui/jni/Utils.h
        hwui/jni/YuvToJpegEncoder.cpp
        hwui/jni/YuvToJpegEncoder.h
        hwui/pipeline/skia/AnimatedDrawables.h
        hwui/pipeline/skia/ATraceMemoryDump.cpp
        hwui/pipeline/skia/ATraceMemoryDump.h
        hwui/pipeline/skia/BackdropFilterDrawable.cpp
        hwui/pipeline/skia/BackdropFilterDrawable.h
        hwui/pipeline/skia/DumpOpsCanvas.h
        hwui/pipeline/skia/FunctorDrawable.h
        hwui/pipeline/skia/GLFunctorDrawable.cpp
        hwui/pipeline/skia/GLFunctorDrawable.h
        hwui/pipeline/skia/HolePunch.cpp
        hwui/pipeline/skia/HolePunch.h
        hwui/pipeline/skia/LayerDrawable.cpp
        hwui/pipeline/skia/LayerDrawable.h
        hwui/pipeline/skia/RenderNodeDrawable.cpp
        hwui/pipeline/skia/RenderNodeDrawable.h
        hwui/pipeline/skia/ReorderBarrierDrawables.cpp
        hwui/pipeline/skia/ReorderBarrierDrawables.h
        hwui/pipeline/skia/ShaderCache.cpp
        hwui/pipeline/skia/ShaderCache.h
        hwui/pipeline/skia/SkiaCpuPipeline.cpp
        hwui/pipeline/skia/SkiaCpuPipeline.h
        hwui/pipeline/skia/SkiaDisplayList.cpp
        hwui/pipeline/skia/SkiaDisplayList.h
        hwui/pipeline/skia/SkiaGpuPipeline.cpp
        hwui/pipeline/skia/SkiaLayer.h
        hwui/pipeline/skia/SkiaMemoryTracer.cpp
        hwui/pipeline/skia/SkiaMemoryTracer.h
        hwui/pipeline/skia/SkiaOpenGLPipeline.cpp
        hwui/pipeline/skia/SkiaPipeline.cpp
        hwui/pipeline/skia/SkiaPipeline.h
        hwui/pipeline/skia/SkiaProfileRenderer.cpp
        hwui/pipeline/skia/SkiaProfileRenderer.h
        hwui/pipeline/skia/SkiaRecordingCanvas.cpp
        hwui/pipeline/skia/SkiaRecordingCanvas.h
        hwui/pipeline/skia/SkiaUtils.h
        hwui/pipeline/skia/SkiaVulkanPipeline.cpp
        hwui/pipeline/skia/StretchMask.cpp
        hwui/pipeline/skia/StretchMask.h
        hwui/pipeline/skia/TransformCanvas.cpp
        hwui/pipeline/skia/TransformCanvas.h
        hwui/pipeline/skia/VkFunctorDrawable.cpp
        hwui/pipeline/skia/VkFunctorDrawable.h
        hwui/pipeline/skia/VkInteropFunctorDrawable.cpp
        hwui/pipeline/skia/VkInteropFunctorDrawable.h
        hwui/platform/android/pipeline/skia/SkiaGpuPipeline.h
        hwui/platform/android/pipeline/skia/SkiaOpenGLPipeline.h
        hwui/platform/android/pipeline/skia/SkiaVulkanPipeline.h
        hwui/platform/android/thread/CommonPoolBase.h
        hwui/platform/android/thread/ThreadBase.h
        hwui/platform/darwin/utils/SharedLib.cpp
        hwui/platform/host/pipeline/skia/SkiaGpuPipeline.h
        hwui/platform/host/pipeline/skia/SkiaOpenGLPipeline.h
        hwui/platform/host/pipeline/skia/SkiaVulkanPipeline.h
        hwui/platform/host/renderthread/CacheManager.cpp
        hwui/platform/host/renderthread/HintSessionWrapper.cpp
        hwui/platform/host/renderthread/ReliableSurface.cpp
        hwui/platform/host/renderthread/RenderThread.cpp
        hwui/platform/host/thread/CommonPoolBase.h
        hwui/platform/host/thread/ThreadBase.h
        hwui/platform/host/utils/MessageHandler.h
        hwui/platform/host/ProfileDataContainer.cpp
        hwui/platform/host/Readback.cpp
        hwui/platform/host/WebViewFunctorManager.cpp
        hwui/platform/linux/utils/SharedLib.cpp
        hwui/private/hwui/DrawGlInfo.h
        hwui/private/hwui/DrawVkInfo.h
        hwui/private/hwui/WebViewFunctor.h
        hwui/renderstate/RenderState.cpp
        hwui/renderstate/RenderState.h
        hwui/renderthread/CacheManager.cpp
        hwui/renderthread/CacheManager.h
        hwui/renderthread/CanvasContext.cpp
        hwui/renderthread/CanvasContext.h
        hwui/renderthread/DrawFrameTask.cpp
        hwui/renderthread/DrawFrameTask.h
        hwui/renderthread/EglManager.cpp
        hwui/renderthread/EglManager.h
        hwui/renderthread/Frame.cpp
        hwui/renderthread/Frame.h
        hwui/renderthread/HardwareBufferRenderParams.h
        hwui/renderthread/HintSessionWrapper.cpp
        hwui/renderthread/HintSessionWrapper.h
        hwui/renderthread/IRenderPipeline.h
        hwui/renderthread/ReliableSurface.cpp
        hwui/renderthread/ReliableSurface.h
        hwui/renderthread/RenderEffectCapabilityQuery.cpp
        hwui/renderthread/RenderEffectCapabilityQuery.h
        hwui/renderthread/RenderProxy.cpp
        hwui/renderthread/RenderProxy.h
        hwui/renderthread/RenderTask.cpp
        hwui/renderthread/RenderTask.h
        hwui/renderthread/RenderThread.cpp
        hwui/renderthread/RenderThread.h
        hwui/renderthread/TimeLord.cpp
        hwui/renderthread/TimeLord.h
        hwui/renderthread/VulkanManager.cpp
        hwui/renderthread/VulkanManager.h
        hwui/renderthread/VulkanSurface.cpp
        hwui/renderthread/VulkanSurface.h
        hwui/service/GraphicsStatsService.cpp
        hwui/service/GraphicsStatsService.h
        hwui/shader/BlurShader.cpp
        hwui/shader/BlurShader.h
        hwui/tests/common/scenes/BackdropBlur.cpp
        hwui/tests/common/scenes/BitmapFillrate.cpp
        hwui/tests/common/scenes/BitmapShaders.cpp
        hwui/tests/common/scenes/ClippingAnimation.cpp
        hwui/tests/common/scenes/GlyphStressAnimation.cpp
        hwui/tests/common/scenes/HwBitmap565.cpp
        hwui/tests/common/scenes/HwBitmapInCompositeShader.cpp
        hwui/tests/common/scenes/HwLayerAnimation.cpp
        hwui/tests/common/scenes/HwLayerSizeAnimation.cpp
        hwui/tests/common/scenes/JankyScene.cpp
        hwui/tests/common/scenes/ListOfFadedTextAnimation.cpp
        hwui/tests/common/scenes/ListViewAnimation.cpp
        hwui/tests/common/scenes/MagnifierAnimation.cpp
        hwui/tests/common/scenes/OpPropAnimation.cpp
        hwui/tests/common/scenes/OvalAnimation.cpp
        hwui/tests/common/scenes/PartialDamageAnimation.cpp
        hwui/tests/common/scenes/PathClippingAnimation.cpp
        hwui/tests/common/scenes/ReadbackFromHardwareBitmap.cpp
        hwui/tests/common/scenes/RecentsAnimation.cpp
        hwui/tests/common/scenes/RectGridAnimation.cpp
        hwui/tests/common/scenes/RoundRectClippingAnimation.cpp
        hwui/tests/common/scenes/SaveLayer2Animation.cpp
        hwui/tests/common/scenes/SaveLayerAnimation.cpp
        hwui/tests/common/scenes/ShadowGrid2Animation.cpp
        hwui/tests/common/scenes/ShadowGridAnimation.cpp
        hwui/tests/common/scenes/ShadowShaderAnimation.cpp
        hwui/tests/common/scenes/ShapeAnimation.cpp
        hwui/tests/common/scenes/SimpleColorMatrixAnimation.cpp
        hwui/tests/common/scenes/SimpleGradientAnimation.cpp
        hwui/tests/common/scenes/StretchyListViewAnimation.cpp
        hwui/tests/common/scenes/TestSceneBase.h
        hwui/tests/common/scenes/TextAnimation.cpp
        hwui/tests/common/scenes/TvApp.cpp
        hwui/tests/common/scenes/WindowBlurKawase.cpp
        hwui/tests/common/scenes/WindowBlurSkia.cpp
        hwui/tests/common/BitmapAllocationTestUtils.h
        hwui/tests/common/CallCountingCanvas.h
        hwui/tests/common/LeakChecker.cpp
        hwui/tests/common/LeakChecker.h
        hwui/tests/common/TestContext.cpp
        hwui/tests/common/TestContext.h
        hwui/tests/common/TestListViewSceneBase.cpp
        hwui/tests/common/TestListViewSceneBase.h
        hwui/tests/common/TestScene.cpp
        hwui/tests/common/TestScene.h
        hwui/tests/common/TestUtils.cpp
        hwui/tests/common/TestUtils.h
        hwui/tests/macrobench/main.cpp
        hwui/tests/macrobench/TestSceneRunner.cpp
        hwui/tests/microbench/CanvasOpBench.cpp
        hwui/tests/microbench/DisplayListCanvasBench.cpp
        hwui/tests/microbench/LinearAllocatorBench.cpp
        hwui/tests/microbench/main.cpp
        hwui/tests/microbench/PathParserBench.cpp
        hwui/tests/microbench/RenderNodeBench.cpp
        hwui/tests/unit/ABitmapTests.cpp
        hwui/tests/unit/AutoBackendTextureReleaseTests.cpp
        hwui/tests/unit/CacheManagerTests.cpp
        hwui/tests/unit/CanvasContextTests.cpp
        hwui/tests/unit/CanvasFrontendTests.cpp
        hwui/tests/unit/CanvasOpTests.cpp
        hwui/tests/unit/CommonPoolTests.cpp
        hwui/tests/unit/DamageAccumulatorTests.cpp
        hwui/tests/unit/DeferredLayerUpdaterTests.cpp
        hwui/tests/unit/DrawTextFunctorTest.cpp
        hwui/tests/unit/EglManagerTests.cpp
        hwui/tests/unit/FatalTestCanvas.h
        hwui/tests/unit/FatVectorTests.cpp
        hwui/tests/unit/FrameMetricsReporterTests.cpp
        hwui/tests/unit/GraphicsStatsServiceTests.cpp
        hwui/tests/unit/HintSessionWrapperTests.cpp
        hwui/tests/unit/JankTrackerTests.cpp
        hwui/tests/unit/LayerUpdateQueueTests.cpp
        hwui/tests/unit/LinearAllocatorTests.cpp
        hwui/tests/unit/main.cpp
        hwui/tests/unit/MatrixTests.cpp
        hwui/tests/unit/OpBufferTests.cpp
        hwui/tests/unit/PathInterpolatorTests.cpp
        hwui/tests/unit/RenderEffectCapabilityQueryTests.cpp
        hwui/tests/unit/RenderNodeDrawableTests.cpp
        hwui/tests/unit/RenderNodeTests.cpp
        hwui/tests/unit/RenderPropertiesTests.cpp
        hwui/tests/unit/RenderThreadTests.cpp
        hwui/tests/unit/ShaderCacheTests.cpp
        hwui/tests/unit/SkiaBehaviorTests.cpp
        hwui/tests/unit/SkiaCanvasTests.cpp
        hwui/tests/unit/SkiaDisplayListTests.cpp
        hwui/tests/unit/SkiaPipelineTests.cpp
        hwui/tests/unit/SkiaRenderPropertiesTests.cpp
        hwui/tests/unit/StretchEffectTests.cpp
        hwui/tests/unit/StringUtilsTests.cpp
        hwui/tests/unit/TestUtilsTests.cpp
        hwui/tests/unit/ThreadBaseTests.cpp
        hwui/tests/unit/TypefaceTests.cpp
        hwui/tests/unit/UnderlineTest.cpp
        hwui/tests/unit/VectorDrawableTests.cpp
        hwui/tests/unit/WebViewFunctorManagerTests.cpp
        hwui/thread/CommonPool.cpp
        hwui/thread/CommonPool.h
        hwui/thread/WorkQueue.h
        hwui/utils/AutoMalloc.h
        hwui/utils/Blur.cpp
        hwui/utils/Blur.h
        hwui/utils/Color.cpp
        hwui/utils/Color.h
        hwui/utils/ForceDark.h
        hwui/utils/GLUtils.cpp
        hwui/utils/GLUtils.h
        hwui/utils/LinearAllocator.cpp
        hwui/utils/LinearAllocator.h
        hwui/utils/Macros.h
        hwui/utils/MathUtils.h
        hwui/utils/NdkUtils.cpp
        hwui/utils/NdkUtils.h
        hwui/utils/PaintUtils.h
        hwui/utils/Pair.h
        hwui/utils/Result.h
        hwui/utils/RingBuffer.h
        hwui/utils/SharedLib.h
        hwui/utils/StatsUtils.cpp
        hwui/utils/StatsUtils.h
        hwui/utils/StringUtils.cpp
        hwui/utils/StringUtils.h
        hwui/utils/TimeUtils.h
        hwui/utils/Timing.h
        hwui/utils/TypefaceUtils.cpp
        hwui/utils/TypefaceUtils.h
        hwui/utils/TypeLogic.h
        hwui/utils/VectorDrawableUtils.cpp
        hwui/utils/VectorDrawableUtils.h
        hwui/AnimationContext.cpp
        hwui/AnimationContext.h
        hwui/Animator.cpp
        hwui/Animator.h
        hwui/AnimatorManager.cpp
        hwui/AnimatorManager.h
        hwui/AutoBackendTextureRelease.cpp
        hwui/AutoBackendTextureRelease.h
        hwui/CanvasProperty.h
        hwui/CanvasTransform.cpp
        hwui/CanvasTransform.h
        hwui/ColorFilter.h
        hwui/ColorMode.h
        hwui/CopyRequest.h
        hwui/DamageAccumulator.cpp
        hwui/DamageAccumulator.h
        hwui/Debug.h
        hwui/DeferredLayerUpdater.cpp
        hwui/DeferredLayerUpdater.h
        hwui/DeviceInfo.cpp
        hwui/DeviceInfo.h
        hwui/DisplayList.h
        hwui/FeatureFlags.h
        hwui/FrameInfo.cpp
        hwui/FrameInfo.h
        hwui/FrameInfoVisualizer.cpp
        hwui/FrameInfoVisualizer.h
        hwui/FrameMetricsObserver.h
        hwui/FrameMetricsReporter.cpp
        hwui/FrameMetricsReporter.h
        hwui/Gainmap.cpp
        hwui/Gainmap.h
        hwui/HardwareBitmapUploader.cpp
        hwui/HardwareBitmapUploader.h
        hwui/IContextFactory.h
        hwui/Interpolator.cpp
        hwui/Interpolator.h
        hwui/IProfileRenderer.h
        hwui/JankTracker.cpp
        hwui/JankTracker.h
        hwui/Layer.cpp
        hwui/Layer.h
        hwui/LayerUpdateQueue.cpp
        hwui/LayerUpdateQueue.h
        hwui/Lighting.h
        hwui/LightingInfo.cpp
        hwui/LightingInfo.h
        hwui/Matrix.cpp
        hwui/Matrix.h
        hwui/MemoryPolicy.cpp
        hwui/MemoryPolicy.h
        hwui/Mesh.cpp
        hwui/Mesh.h
        hwui/NinePatchUtils.h
        hwui/Outline.h
        hwui/PathParser.cpp
        hwui/PathParser.h
        hwui/ProfileData.cpp
        hwui/ProfileData.h
        hwui/ProfileDataContainer.cpp
        hwui/ProfileDataContainer.h
        hwui/Properties.cpp
        hwui/Properties.h
        hwui/PropertyValuesAnimatorSet.cpp
        hwui/PropertyValuesAnimatorSet.h
        hwui/PropertyValuesHolder.cpp
        hwui/PropertyValuesHolder.h
        hwui/Readback.cpp
        hwui/Readback.h
        hwui/RecordingCanvas.cpp
        hwui/RecordingCanvas.h
        hwui/Rect.h
        hwui/RenderNode.cpp
        hwui/RenderNode.h
        hwui/RenderProperties.cpp
        hwui/RenderProperties.h
        hwui/RevealClip.h
        hwui/RootRenderNode.cpp
        hwui/RootRenderNode.h
        hwui/SafeMath.h
        hwui/SaveFlags.h
        hwui/SkiaCanvas.cpp
        hwui/SkiaCanvas.h
        hwui/SkiaInterpolator.cpp
        hwui/SkiaInterpolator.h
        hwui/SkippedFrameInfo.h
        hwui/SwapBehavior.h
        hwui/Tonemapper.cpp
        hwui/Tonemapper.h
        hwui/TreeInfo.cpp
        hwui/TreeInfo.h
        hwui/UvMapper.h
        hwui/Vector.h
        hwui/VectorDrawable.cpp
        hwui/VectorDrawable.h
        hwui/Vertex.h
        hwui/VertexBuffer.h
        hwui/WebViewFunctorManager.cpp
        hwui/WebViewFunctorManager.h
        incident/include/incident/incident_report.h
        incident/include_priv/android/os/IncidentReportArgs.h
        incident/src/incident_report.cpp
        incident/src/IncidentReportArgs.cpp
        incident/tests/IncidentReportArgs_test.cpp
        incident/tests/IncidentReportRequest_test.cpp
        input/tests/mocks/MockSprite.h
        input/tests/mocks/MockSpriteController.h
        input/tests/PointerController_test.cpp
        input/MouseCursorController.cpp
        input/MouseCursorController.h
        input/PointerController.cpp
        input/PointerController.h
        input/PointerControllerContext.cpp
        input/PointerControllerContext.h
        input/SpriteController.cpp
        input/SpriteController.h
        input/SpriteIcon.cpp
        input/SpriteIcon.h
        input/TouchSpotController.cpp
        input/TouchSpotController.h
        nativehelper_jvm/file_descriptor_jni.c
        nativehelper_jvm/JniConstants.c
        nativehelper_jvm/JniConstants.h
        nativehelper_jvm/JNIPlatformHelp.c
        protoutil/include/android/util/EncodedBuffer.h
        protoutil/include/android/util/protobuf.h
        protoutil/include/android/util/ProtoFileReader.h
        protoutil/include/android/util/ProtoOutputStream.h
        protoutil/include/android/util/ProtoReader.h
        protoutil/src/EncodedBuffer.cpp
        protoutil/src/protobuf.cpp
        protoutil/src/ProtoFileReader.cpp
        protoutil/src/ProtoOutputStream.cpp
        protoutil/src/ProtoReader.cpp
        protoutil/tests/EncodedBuffer_test.cpp
        protoutil/tests/protobuf_test.cpp
        protoutil/tests/ProtoOutputStream_test.cpp
        services/include/android/content/ComponentName.h
        services/include/android/os/DropBoxManager.h
        services/src/content/ComponentName.cpp
        services/src/os/DropBoxManager.cpp
        storage/include/storage/IMountService.h
        storage/include/storage/IMountServiceListener.h
        storage/include/storage/IMountShutdownObserver.h
        storage/include/storage/IObbActionListener.h
        storage/include/storage/ObbInfo.h
        storage/IMountService.cpp
        storage/IMountServiceListener.cpp
        storage/IMountShutdownObserver.cpp
        storage/IObbActionListener.cpp
        storage/ObbInfo.cpp
        usb/tests/AccessoryChat/accessorychat/linux/usb/f_accessory.h
        usb/tests/AccessoryChat/accessorychat/accessorychat.c
        usb/tests/accessorytest/accessory.c
        usb/tests/accessorytest/accessory.h
        usb/tests/accessorytest/audio.c
        usb/tests/accessorytest/f_accessory.h
        usb/tests/accessorytest/hid.c
        usb/tests/accessorytest/usb.c)
